import { Roboto, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

const plusJarkata = Plus_Jakarta_Sans({
  variable: "--font-plus-Jarkata",
  weight: ["200" , "300" , "400" , "500" , "600" , "700" , "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Paceflow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={twMerge("antialiased", robotoSans.variable, plusJarkata.variable)}>
        {children}
      </body>
    </html>
  );
}
